<?xml version="1.0" encoding="utf-8"?><Database Name="University" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=194.44.93.225;Initial Catalog=University;User ID=koziar;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="LinqToSQL.Properties.Settings" SettingsPropertyName="UniversityConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Groups">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Department" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Groups_Student" Member="Student" ThisKey="Id" OtherKey="IdGroup" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Student">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IdGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Groups_Student" Member="Groups" ThisKey="IdGroup" OtherKey="Id" Type="Groups" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>